### ISSUE TITLE
Automatically add the file extension when adding page definitions and test cases

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#12]
Change the pop-up menu options for the page-definitions, test-cases, test-suites (and test-routines) folders:

- page-definitions - "New Page",  "New Folder"
- test-cases -  "New Test Case", "New Folder"
- test-suites - "New Test Suite", "New Folder"
- other folders - "New File" and "New Folder"

When the user chooses "New Page/New Test Case/ New Test Suite" they won't enter the file extension, i.e. right now they have to enter "ContactInfo.page" but will enter "ContactInfo" instead.  The page, test case or test suite will continue to be saved with the .page, .tcase or .tsuite file extension

**Comment by hanglequan1991** [comment]
Hi @veebs , @quockhanh 
Please review this PR https://github.com/rockmelonqa/ide/pull/52

**Comment by brogreenmoon** [comment]
Resolved.  I added a page definition, test case and test suite with the name "hello" and the .page, .tcase and .tsuite file extensions were added automatically:

![image](https://user-images.githubusercontent.com/114720205/233899616-4d429243-d83b-45ad-a10b-bbee7a83a02c.png)

**Comment by brogreenmoon** [comment]
The side effect of this change is that if you enter "hello.txt" as the page definition/test case/test suite name it automatically adds the .page, making the file name "hello.txt.page", whereas previously you could files with different extensions.  This is by design.  We might add support for a "New File" option later that allows files of other types to be created in the IDE.
