### ISSUE TITLE
Verify Url causes the codegen process to fail

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#19]

**Comment by brogreenmoon** [comment]
This fails due to:

Parsing: thelakes.page

Parsing: thelakes.tsuite

Parsing: thelakes.tcase

Cleaning folder: C:\Rockmelon\TheLakes\output-code

Creating file: 'PageDefinitions.cs'

Creating file: 'Pages\ThelakesPage.cs'

Creating file: 'TestCases\ThelakesTestCase.cs'

Creating file: 'TestSuites\ThelakesTestSuite.cs'

Creating file: 'Support/LocatorHelper.cs'

Creating file: 'Support/RmSingleCaseSuiteBase.cs'

Creating file: 'AutomationTests.csproj'

Creating file: 'Usings.cs'

Creating file: '.runsettings'

Creating file: '.code-metadata'

Executing: 'dotnet build'

Error: Command "dotnet build" failed:
MSBuild version 17.4.0+18d5aef85 for .NET
Determining projects to restore...
Restored C:\Rockmelon\TheLakes\output-code\AutomationTests.csproj (in 399 ms).
C:\Rockmelon\TheLakes\output-code\TestCases\ThelakesTestCase.cs(17,22): error CS1503: Argument 1: cannot convert from 'Microsoft.Playwright.IPage' to 'Microsoft.Playwright.ILocator' [C:\Rockmelon\TheLakes\output-code\AutomationTests.csproj]

Build FAILED.

C:\Rockmelon\TheLakes\output-code\TestCases\ThelakesTestCase.cs(17,22): error CS1503: Argument 1: cannot convert from 'Microsoft.Playwright.IPage' to 'Microsoft.Playwright.ILocator' [C:\Rockmelon\TheLakes\output-code\AutomationTests.csproj]
0 Warning(s)
1 Error(s)

Time Elapsed 00:00:01.42

![image](https://user-images.githubusercontent.com/114720205/233557868-ced983e1-4404-4929-8603-48c3a28cb0ac.png)

**Comment by brogreenmoon** [comment]
Implemented.

![image](https://github.com/rockmelonqa/ide/assets/114720205/d9e1e9e7-f7ed-43a4-bc1a-3c9586157931)

is implemented as:

![image](https://github.com/rockmelonqa/ide/assets/114720205/2ece4e59-d0c3-47a2-9ac9-8f2624438d53)

and executes successfully.
